const sampleListings = [
  {
    title: "Luxury Beach Villa",
    description: "Relax in this beautiful beachfront villa with stunning ocean views and a private pool.",
    image: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Modern Apartment in Hyderabad",
    description: "A stylish modern apartment located in the heart of Hyderabad, perfect for city explorers.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 1800,
    location: "Hyderabad",
    country: "India",
  },
  {
    title: "Cozy Mountain Cabin",
    description: "Escape to this peaceful wooden cabin surrounded by mountains and forests.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
    price: 3200,
    location: "Manali",
    country: "India",
  },
  {
    title: "Luxury Villa in Bali",
    description: "Enjoy a tropical vacation in this luxurious villa featuring a private pool and garden.",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=60",
    price: 5500,
    location: "Bali",
    country: "Indonesia",
  },
  {
    title: "Ocean View Apartment",
    description: "Wake up to breathtaking ocean views from this modern apartment near the beach.",
    image: "https://images.unsplash.com/photo-1505881502353-a1986add3762?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Miami",
    country: "United States",
  },
  {
    title: "Traditional House in Jaipur",
    description: "Experience traditional Indian architecture in this beautifully designed house.",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=60",
    price: 2200,
    location: "Jaipur",
    country: "India",
  },
  {
    title: "Forest Treehouse",
    description: "Stay among the trees in this unique treehouse surrounded by lush greenery.",
    image: "https://images.unsplash.com/photo-1520984032042-162d526883e0?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Kerala",
    country: "India",
  },
  {
    title: "Modern Loft in New York",
    description: "A stylish loft in the heart of New York City close to restaurants and attractions.",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=60",
    price: 7500,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Lakefront Wooden Cabin",
    description: "Enjoy peaceful mornings beside the lake in this charming wooden cabin.",
    image: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Apartment in Dubai",
    description: "Stay in a luxurious apartment with spectacular city views and modern interiors.",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=60",
    price: 8500,
    location: "Dubai",
    country: "United Arab Emirates",
  },
  {
    title: "Beach House in Maldives",
    description: "Enjoy a dream vacation surrounded by crystal-clear water and white sandy beaches.",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=60",
    price: 12000,
    location: "Maldives",
    country: "Maldives",
  },
  {
    title: "Cozy Cottage in Ooty",
    description: "A peaceful cottage surrounded by green hills and beautiful tea plantations.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    price: 2500,
    location: "Ooty",
    country: "India",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience Italian countryside living in this charming historic villa.",
    image: "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?auto=format&fit=crop&w=800&q=60",
    price: 6800,
    location: "Tuscany",
    country: "Italy",
  },
  {
    title: "Ski Chalet in Switzerland",
    description: "A beautiful alpine chalet with breathtaking mountain views and ski access.",
    image: "https://images.unsplash.com/photo-1548777123-e216912df7d8?auto=format&fit=crop&w=800&q=60",
    price: 9000,
    location: "Zermatt",
    country: "Switzerland",
  },
  {
    title: "Minimalist Home in Tokyo",
    description: "Stay in a modern minimalist home close to Tokyo's shopping and entertainment districts.",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=60",
    price: 5000,
    location: "Tokyo",
    country: "Japan",
  },
  {
    title: "Desert Villa in Rajasthan",
    description: "Experience desert living in this traditional yet luxurious villa with sunset views.",
    image: "https://images.unsplash.com/photo-1470214304380-aadaedcfff1b?auto=format&fit=crop&w=800&q=60",
    price: 3000,
    location: "Jaisalmer",
    country: "India",
  },
  {
    title: "Cliffside Villa in Greece",
    description: "Enjoy breathtaking Mediterranean views from this stunning cliffside villa.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=60",
    price: 7500,
    location: "Santorini",
    country: "Greece",
  },
  {
    title: "Countryside Cottage",
    description: "A charming countryside cottage offering a peaceful escape from the city.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=60",
    price: 4200,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Modern Beach House",
    description: "A stylish beach house with spacious rooms and stunning Pacific Ocean views.",
    image: "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=800&q=60",
    price: 6200,
    location: "California",
    country: "United States",
  },
  {
    title: "Eco Retreat in Costa Rica",
    description: "Reconnect with nature in this eco-friendly retreat surrounded by tropical forests.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=800&q=60",
    price: 3800,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Royal Palace Stay",
    description: "Experience royal-style living in this magnificent heritage property.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
    price: 6500,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Mountain View Resort",
    description: "Wake up to beautiful mountain views from this peaceful hillside retreat.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
    price: 2900,
    location: "Shimla",
    country: "India",
  },
  {
    title: "Seaside Cottage",
    description: "A charming cottage just steps away from the sea with a relaxing coastal atmosphere.",
    image: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60",
    price: 2600,
    location: "Pondicherry",
    country: "India",
  },
  {
    title: "Luxury Penthouse",
    description: "Enjoy premium city living in this spacious penthouse with panoramic views.",
    image: "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=800&q=60",
    price: 9500,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Riverside Cabin",
    description: "Relax beside the river in this cozy cabin surrounded by beautiful natural scenery.",
    image: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Rishikesh",
    country: "India",
  },
  {
    title: "Luxury Villa in Phuket",
    description: "A tropical villa with an infinity pool and stunning views of the Andaman Sea.",
    image: "https://images.unsplash.com/photo-1582610116397-edb318620f90?auto=format&fit=crop&w=800&q=60",
    price: 7000,
    location: "Phuket",
    country: "Thailand",
  },
  {
    title: "Cozy Apartment in Paris",
    description: "Stay in a beautiful Parisian apartment close to cafes, museums, and famous landmarks.",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=60",
    price: 5800,
    location: "Paris",
    country: "France",
  },
  {
    title: "Alpine Lodge",
    description: "A cozy mountain lodge perfect for skiing, hiking, and enjoying the Swiss Alps.",
    image: "https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=800&q=60",
    price: 7200,
    location: "Interlaken",
    country: "Switzerland",
  },
  {
    title: "Island Villa",
    description: "Enjoy complete privacy in this beautiful island villa surrounded by turquoise waters.",
    image: "https://images.unsplash.com/photo-1493552152660-f915ab47ae9d?auto=format&fit=crop&w=800&q=60",
    price: 11000,
    location: "Fiji",
    country: "Fiji",
  },
  {
    title: "Modern Home in Seoul",
    description: "A contemporary home located near Seoul's best shopping, food, and entertainment.",
    image: "https://images.unsplash.com/photo-1538485399081-7c8972e3a3ee?auto=format&fit=crop&w=800&q=60",
    price: 4500,
    location: "Seoul",
    country: "South Korea",
  },
  {
    title: "Safari Lodge",
    description: "Experience wildlife and nature while staying in this comfortable luxury safari lodge.",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=60",
    price: 8500,
    location: "Serengeti",
    country: "Tanzania",
  },
  {
    title: "Historic Home in Amsterdam",
    description: "Stay in a charming historic home overlooking one of Amsterdam's famous canals.",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=800&q=60",
    price: 4900,
    location: "Amsterdam",
    country: "Netherlands",
  },
  {
    title: "Luxury Stay in London",
    description: "A sophisticated apartment in central London with elegant interiors and modern facilities.",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
    price: 6500,
    location: "London",
    country: "United Kingdom",
  },
  {
    title: "Forest Retreat",
    description: "A peaceful forest retreat perfect for disconnecting from the busy city lifestyle.",
    image: "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?auto=format&fit=crop&w=800&q=60",
    price: 2400,
    location: "Coorg",
    country: "India",
  },
  {
    title: "Luxury Stay in New York",
    description: "Experience New York City from this stylish apartment with incredible skyline views.",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=800&q=60",
    price: 8000,
    location: "New York",
    country: "United States",
  },
  {
    title: "Beach Resort in Goa",
    description: "A relaxing beach resort with beautiful rooms, palm trees, and easy beach access.",
    image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=60",
    price: 3500,
    location: "Goa",
    country: "India",
  },
  {
    title: "Villa in Mykonos",
    description: "Stay in a beautiful whitewashed villa overlooking the blue waters of the Aegean Sea.",
    image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=800&q=60",
    price: 8200,
    location: "Mykonos",
    country: "Greece",
  },
  {
    title: "Luxury Desert Camp",
    description: "Enjoy a unique luxury camping experience under the stars in the Arabian desert.",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60",
    price: 5500,
    location: "Dubai",
    country: "United Arab Emirates",
  },
  {
    title: "Mountain Cabin in Canada",
    description: "A cozy cabin surrounded by the Canadian Rockies with amazing views and hiking trails.",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60",
    price: 4200,
    location: "Banff",
    country: "Canada",
  },
  {
    title: "Modern Villa in Barcelona",
    description: "A stylish modern villa perfect for exploring Barcelona's beaches, architecture, and nightlife.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=60",
    price: 6100,
    location: "Barcelona",
    country: "Spain",
  },
  {
    title: "Lake House in New Zealand",
    description: "Enjoy breathtaking lake and mountain views from this peaceful New Zealand getaway.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
    price: 3900,
    location: "Queenstown",
    country: "New Zealand",
  },
  {
    title: "Traditional Villa in Bali",
    description: "Experience traditional Balinese architecture surrounded by tropical gardens and nature.",
    image: "https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?auto=format&fit=crop&w=800&q=60",
    price: 4800,
    location: "Ubud",
    country: "Indonesia",
  },
  {
    title: "Luxury Apartment in Singapore",
    description: "A premium apartment with modern facilities and stunning views of the city skyline.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=60",
    price: 6800,
    location: "Singapore",
    country: "Singapore",
  },
  {
    title: "Countryside Farmhouse",
    description: "Escape the city and enjoy peaceful countryside living in this beautiful farmhouse.",
    image: "https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=800&q=60",
    price: 2700,
    location: "Cotswolds",
    country: "United Kingdom",
  },
  {
    title: "Luxury Villa in Cape Town",
    description: "A stunning villa offering spectacular ocean and mountain views near Cape Town.",
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&w=800&q=60",
    price: 6200,
    location: "Cape Town",
    country: "South Africa",
  },
  {
    title: "Modern Apartment in Sydney",
    description: "Stay in a modern apartment close to Sydney's beaches, restaurants, and attractions.",
    image: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=800&q=60",
    price: 5200,
    location: "Sydney",
    country: "Australia",
  },
  {
    title: "Beach Cottage in Sri Lanka",
    description: "Relax in this charming coastal cottage surrounded by tropical scenery and beautiful beaches.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=800&q=60",
    price: 2300,
    location: "Galle",
    country: "Sri Lanka",
  },
  {
    title: "Luxury Palace in Udaipur",
    description: "Experience royal hospitality in this elegant heritage property overlooking the city and lake.",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=60",
    price: 9000,
    location: "Udaipur",
    country: "India",
  },
  {
    title: "Coastal Villa in Portugal",
    description: "A beautiful coastal villa with ocean views, spacious rooms, and a relaxing atmosphere.",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=60",
    price: 4700,
    location: "Algarve",
    country: "Portugal",
  },
  {
    title: "Snow Cabin in Finland",
    description: "Enjoy a magical winter stay in a cozy cabin surrounded by snowy forests.",
    image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=800&q=60",
    price: 5800,
    location: "Lapland",
    country: "Finland",
  },
  {
    title: "Luxury House in Los Angeles",
    description: "A spacious luxury home with a pool and beautiful city views in Los Angeles.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 8500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Mountain Retreat in Nepal",
    description: "A peaceful mountain retreat offering spectacular Himalayan views and fresh mountain air.",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=60",
    price: 2800,
    location: "Pokhara",
    country: "Nepal",
  },
  {
    title: "Tropical House in Mauritius",
    description: "Enjoy a relaxing island vacation in this beautiful tropical house near the ocean.",
    image: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=800&q=60",
    price: 5200,
    location: "Mauritius",
    country: "Mauritius",
  },
];

module.exports = { data: sampleListings };